### ISSUE TITLE
[Bug-Help] From 8.2.5-debian-10-r6 onwards, image get stuck after 

### ISSUE THREAD

**Issue by 1naboki1** [bitnami/bitnami-docker-grafana#20] opened 2021-12-10 09:54 UTC
**Description**

I am using bitnami/grafana-operator helm chart 1.5.3 to deploy grafana instances in a rke2 K8 Cluster, and for deploying ArgoCD 2.1.7 is in use.
In the bitnami/8.2.5-debian-10-r6 the image gets stuck infintly after the init container has finished. Also i can definitly point this issue to this release (and onwards) as the Init process in dockerfile was completly rewritten.

**Steps to reproduce the issue:**

Provison bitnami/8.2.5-debian-10-r6 using the grafana operator in a rke2 Cluster

**Describe the results you received:**

- GRAFANA-PLUGINS-INIT

```
lvl=info msg="migrations completed" logger=migrator performed=346 skipped=0 duration=1.143731413s
lvl=info msg="Created default admin" logger=sqlstore user=admin
lvl=info msg="Created default organization" logger=sqlstore
lvl=info msg="Starting plugin search" logger=plugins
lvl=info msg="Registering plugin" logger=plugins id=input
lvl=info msg="Live Push Gateway initialization" logger=live.push_http
lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```

- GRAFANA

```
container "grafana" in pod "grafana-deployment-54d8b77d96-hcp92" is waiting to start: PodInitializing
```

containerd doesnt report any issue too

**Describe the results you expected:**

A Running kubernetes pod

**Version**

- Output of `kubectl descrribe`:

```
kubectl describe pod -n monitoring grafana-deployment-54d8b77d96-hcp92
Name:         grafana-deployment-54d8b77d96-hcp92
Namespace:    monitoring
Priority:     0
Node:         XXX
Start Time:   Fri, 10 Dec 2021 10:41:36 +0100
Labels:       app=grafana
              pod-template-hash=54d8b77d96
Annotations:  cni.projectcalico.org/podIP: 10.42.2.44/32
              cni.projectcalico.org/podIPs: 10.42.2.44/32
              kubectl.kubernetes.io/restartedAt: 2021-12-09T14:35:19Z
              kubernetes.io/psp: global-restricted-psp
              prometheus.io/port: 3000
              prometheus.io/scrape: true
Status:       Pending
IP:           10.42.2.44
IPs:
  IP:           10.42.2.44
Controlled By:  ReplicaSet/grafana-deployment-54d8b77d96
Init Containers:
  grafana-plugins-init:
    Container ID:   containerd://5797b42ad892e99026186054b6ca8e4e249467c5a9cf9d7ea6f81bc879b202eb
    Image:          XXX/bitnami/grafana:8.2.5-debian-10-r6
    Image ID:       XXX/bitnami/grafana@sha256:86bb6a3f01351a1dd809491554e5f02a1bed72bcc58be0d8f5fc5f7845864b5a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 10 Dec 2021 10:41:37 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:     250m
      memory:  128Mi
    Environment:
      GRAFANA_PLUGINS:  
    Mounts:
      /opt/plugins from grafana-plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-48gbr (ro)
Containers:
  grafana:
    Container ID:  
    Image:         XXX/bitnami/grafana:8.2.5-debian-10-r6
    Image ID:      
    Port:          3000/TCP
    Host Port:     0/TCP
    Args:
      -config=/etc/grafana/grafana.ini
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Liveness:   http-get http://:3000/api/health delay=60s timeout=30s period=10s #success=1 #failure=10
    Readiness:  http-get http://:3000/api/health delay=5s timeout=3s period=10s #success=1 #failure=1
    Environment:
      LAST_CONFIG:                 256d75d4e7984be3c0ef73a06d9142168aa88036aeef8922b8304d3930519061
      LAST_DATASOURCES:            b0e4d0dbe8305b23468f1be66ba2bdc37994b63d373545ab1907ba6e6307e2ed
      GF_SECURITY_ADMIN_USER:      <set to the key 'GF_SECURITY_ADMIN_USER' in secret 'grafana-admin-credentials'>      Optional: false
      GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'GF_SECURITY_ADMIN_PASSWORD' in secret 'grafana-admin-credentials'>  Optional: false
    Mounts:
      /etc/grafana/ from grafana-config (rw)
      /etc/grafana/provisioning/datasources from grafana-datasources (rw)
      /var/lib/grafana from grafana-data (rw)
      /var/lib/grafana/plugins from grafana-plugins (rw)
      /var/log/grafana from grafana-logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-48gbr (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  grafana-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-config
    Optional:  false
  grafana-logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  grafana-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  grafana-plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  grafana-datasources:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      grafana-datasources
    Optional:  false
  kube-api-access-48gbr:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m50s  default-scheduler  Successfully assigned monitoring/grafana-deployment-54d8b77d96-hcp92 to XXXX
  Normal  Pulled     3m53s  kubelet            Container image "XXXX/bitnami/grafana:8.2.5-debian-10-r6" already present on machine
  Normal  Created    3m53s  kubelet            Created container grafana-plugins-init
  Normal  Started    3m53s  kubelet            Started container grafana-plugins-init
```

**Comment by juan131** [comment] 2021-12-10 12:38
Duplicate of https://github.com/bitnami/bitnami-docker-grafana/issues/17

**Closed by juan131** 2021-12-10 12:38 UTC
